### PR TITLE
Add function to get temperature for DS3231

### PR DESCRIPTION
**Pull request by toannds**
Read temperature from register 0x11 of DS3231
Change the example accordingly

### CODE REVIEW

**Comment by gknauf** [comment]
Hi, I dont want to do another fork for the same topic, so I would like to ask you if you might be willing to update your pull request with the following code which can optionally do a forced temperature conversion.
```C
--- RTClib.cpp.orig	Fri Aug 26 14:18:47 2016
+++ RTClib.cpp	Fri Aug 26 14:22:26 2016
@@ -505,9 +505,16 @@
   //Serial.println( read_i2c_register(DS3231_ADDRESS, DS3231_CONTROL), HEX);
 }
 
-float RTC_DS3231::getTemperature()
-{
-  uint8_t msb, lsb;
+float RTC_DS3231::getTemperature(bool force) {
+  uint8_t msb, lsb, ctrl;
+
+  if (force) {
+    while (read_i2c_register(DS3231_ADDRESS, DS3231_STATUSREG) & 0b00000100); // check for BSY bit
+    ctrl = read_i2c_register(DS3231_ADDRESS, DS3231_CONTROL);
+    write_i2c_register(DS3231_ADDRESS, DS3231_CONTROL, ctrl | 0b00100000);    // set CONV
+    while (read_i2c_register(DS3231_ADDRESS, DS3231_CONTROL) & 0b00100000);   // check for CONV bit
+  }
+
   Wire.beginTransmission(DS3231_ADDRESS);
   Wire._I2C_WRITE(DS3231_TEMPERATUREREG);
   Wire.endTransmission();
################################################################################
--- RTClib.h.orig	Fri Aug 26 14:18:47 2016
+++ RTClib.h	Fri Aug 26 14:23:17 2016
@@ -104,7 +104,8 @@
     static DateTime now();
     static Ds3231SqwPinMode readSqwPinMode();
     static void writeSqwPinMode(Ds3231SqwPinMode mode);
-	static float getTemperature();		// in Celcius degree
+    // without force=true the DS3231 temperature will be converted only every 64 seconds.
+    static float getTemperature(bool force = false);		// in Celcius degree
 };
```

**Comment by ortegafernando** [comment]
Hi, is there any planing to merge it to master brand ? Regards,

**Comment by combs** [comment]
Nice!

**Comment by KunalGautam** [comment]
Awaiting for this feature in RTCLib

**Comment by martin-eden** [comment]
It's a pity that pull requests are not processed here.

I implemented same thing for DS3231 a couple days ago and went here to add pull request. Just to find this one. Two and half years ago.

**Comment by Kanabanarama** [comment]
Also waiting for this feature

**Comment by Phoenix1747** [comment]
Same here

**Comment by Kanabanarama** [comment]
Wow, thank you!

**Pull request merged**
